### ISSUE TITLE
Varnish does not work with multisite setup

### ISSUE THREAD

**Issue by jbrinksmeier** [carlalexander/debops-wordpress#111]
First things first: Thanks a lot for the great work done here :)

When deploying a multisite network following the instructions [here](https://github.com/carlalexander/debops-wordpress/wiki/How-to-create-a-multisite-network), with subdomains, only the root domain is accessible. All additional sites in the network show empty pages with a 444 response code from nginx.

 When running varnishlog and accessing a subdomain site2.wordpress.mysite.com, it shows that there is a cache entry for "/" and then complains that the access host does not match the one that the cache entry has been created for, namely wordpress.mysite.com and returns the 444 response. 

Currently, my workaround is to let the nginx conf for the actual site listen on port 80, disabling varnish that way.

**Comment by carlalexander** [comment]
I've never tried multisite with two levels of subdomains. That said, I don't see why it wouldn't work. Could you show me your configuration?

Based on what you showed me, it should be something like:

``` yml
wordpress__multisite: True
wordpress__multisite_subdomains: True
wordpress__nginx__server_name: [ 'wordpress.mysite.com', 'site2.wordpress.mysite.com' ]
```
