### ISSUE TITLE
Site can't be reached

### ISSUE THREAD

**Issue by zedrickvillas** [carlalexander/debops-wordpress#116]
It seems that something is blocking if an IP is visiting the site too much but not spamming.
is it because of fail2ban?

**Comment by carlalexander** [comment]
How often? It's possible that it's fail2ban. I configured fail2ban with some crude ddos protection.

**Comment by zedrickvillas** [comment]
Yes, i've tried to stop fail2ban via ssh, and was now able to access the site.
Why do u think i was locked by fail2ban?
i was just configuring some settings that time.

**Comment by cezarneaga** [comment]
@zedrickvillas check this here: https://github.com/carlalexander/debops-wordpress/issues/81#issuecomment-228685641 

it helped me.

**Comment by carlalexander** [comment]
It's probably the ddos rule. It bans someone for 2 hours if they spam requests. The default is 300 requests in 5 minute. You can override the defaults if you want. Or turn off that jail.

**Comment by cezarneaga** [comment]
you mean line 60
`fail2ban_bantime: '{{ (60 * 60 * 2) }}'`
in debops.fail2ban/defaults/main.yml
right?

**Comment by cezarneaga** [comment]
i just had a look here and the # Default mail notification method
`fail2ban_mta: 'sendmail'`
shouldnt this be postfix? are you setting it elsewhere to postfix? i never get fail2ban emails

**Comment by carlalexander** [comment]
The default fail2ban action is `action_` which bans without alerting by email. The `sendmail` uses postfix so it works. To get emails, you need to set this option:

```yml
wordpress__fail2ban__default_action: 'action_mwl'
```

It will send those emails to `root@domain.com` so that needs to be a valid address.

The DDOS setting start at line 170:

```yml
# .. envvar:: wordpress__fail2ban__jail_ddos_action
#
# Action performed by ``fail2ban`` when IP address is banned by the DDOS jail.
wordpress__fail2ban__jail_ddos_action: '{{ wordpress__fail2ban__default_action }}'

# .. envvar:: wordpress__fail2ban__jail_ddos_bantime
#
# Length of time in seconds for the DDOS jail ban to persist. (Default: 2 hours)
wordpress__fail2ban__jail_ddos_bantime: '{{ wordpress__fail2ban__default_bantime }}'

# .. envvar:: wordpress__fail2ban__jail_ddos_enabled
#
# Whether the DDOS jail is enabled or not.
wordpress__fail2ban__jail_ddos_enabled: 'true'

# .. envvar:: wordpress__fail2ban__jail_ddos_findtime
#
# Length of time in seconds under which the given ``maxretry`` needs to happen
# to trigger a DDOS ban. (Default: 5 minutes)
wordpress__fail2ban__jail_ddos_findtime: '300'

# .. envvar:: wordpress__fail2ban__jail_ddos_maxretry
#
# Maximum number of requests in the given ``findtime`` to trigger a DDOS ban.
wordpress__fail2ban__jail_ddos_maxretry: '300'
```
