### ISSUE TITLE
Do not create WordPress directory if it exists as a link

### ISSUE THREAD

**Issue by tobeycodes** [carlalexander/debops-wordpress#177]
Related error:

`fatal: []: FAILED! => {"changed": false, "failed": true, "gid": 992, "group": "wordpress", "mode": "0777", "msg": "/var/www/google.com/current already exists as a link", "owner": "wordpress", "path": "/var/www/google.com/current", "size": 10, "state": "link", "uid": 997}`

Related code: 

```
- name: Create WordPress directory
  file:
    path: '{{ wordpress__root }}'
    state: 'directory'
    owner: '{{ wordpress__user_name }}'
    group: '{{ wordpress__user_group }}'
    mode: '0755'
```
