### ISSUE TITLE
TASK [debops.pki : Download public realm contents by host] Fails

### ISSUE THREAD

**Issue by isaiaholoyede** [carlalexander/debops-wordpress#215]
By the way, great job on this playbook! This is not the first time I will be using this playbook. I just pulled the latest release, but I cannot get the playbook to go past that particular task. I believe that I have things setup correctly. 

On close inspection, I noticed that the task is referring to a non-existent directory in the secret folder: `secret/pki/realms/by-host/genesis.rccgla.org/rccgla.org/external/`

This directory exists instead: `secret/pki/realms/by-host/genesis.rccgla.org/domain/external/`

Could you point me in the right direction of what I must have done wrong?

```
TASK [debops.pki : Download public realm contents by host] ***********************************************************************************************************
ok: [genesis.rccgla.org] => (item=[{'name': 'domain', 'acme': False, 'default_subdomains': ['genesis', '*.genesis', '_wildcard_']}, 'external'])
ok: [genesis.rccgla.org] => (item=[{'name': 'domain', 'acme': False, 'default_subdomains': ['genesis', '*.genesis', '_wildcard_']}, 'internal'])
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [genesis.rccgla.org] (item=[{'name': 'rccgla.org', 'acme': True, 'acme_challenge_dir': '/var/www/acme/.well-known/acme-challenge', 'acme_default_subdomains': ['www'], 'acme_subdomains': ['www'], 'default_subdomains': ['www'], 'subdomains': ['www']}, 'external']) => {"changed": false, "item": [{"acme": true, "acme_challenge_dir": "/var/www/acme/.well-known/acme-challenge", "acme_default_subdomains": ["www"], "acme_subdomains": ["www"], "default_subdomains": ["www"], "name": "rccgla.org", "subdomains": ["www"]}, "external"], "msg": "Could not find or access '/Users/isaiaholoyede/Personal/Websites/setup/rccgla.org/inventory/../secret/pki/realms/by-host/genesis.rccgla.org/rccgla.org/external/' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
failed: [genesis.rccgla.org] (item=[{'name': 'rccgla.org', 'acme': True, 'acme_challenge_dir': '/var/www/acme/.well-known/acme-challenge', 'acme_default_subdomains': ['www'], 'acme_subdomains': ['www'], 'default_subdomains': ['www'], 'subdomains': ['www']}, 'internal']) => {"changed": false, "item": [{"acme": true, "acme_challenge_dir": "/var/www/acme/.well-known/acme-challenge", "acme_default_subdomains": ["www"], "acme_subdomains": ["www"], "default_subdomains": ["www"], "name": "rccgla.org", "subdomains": ["www"]}, "internal"], "msg": "Could not find or access '/Users/isaiaholoyede/Personal/Websites/setup/rccgla.org/inventory/../secret/pki/realms/by-host/genesis.rccgla.org/rccgla.org/internal/' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
	to retry, use: --limit @/Users/isaiaholoyede/Personal/Websites/setup/rccgla.org/playbooks/wordpress.retry

PLAY RECAP ***********************************************************************************************************************************************************
genesis.rccgla.org         : ok=190  changed=0    unreachable=0    failed=1
```

**Comment by carlalexander** [comment]
What version of the project are you using? When did you run `debops-update` last? I just did a new release last week because a lot changed with DebOps in the last 6 months so it's possible that that's the issue.

**Comment by isaiaholoyede** [comment]
I am running the latest version. I cleaned out my old project and I did debops-update before running it. I also refreshed my DO droplet a second time and re-ran the project just in case I missed a step, and I still got the same error at the same point.

Let me reclone and try it one more time, starting from scratch again. Will let you know.

**Comment by isaiaholoyede** [comment]
> I am running the latest version. I cleaned out my old project and I did debops-update before running it. I also refreshed my DO droplet a second time and re-ran the project just in case I missed a step, and I still got the same error at the same point.
> 
> Let me reclone and try it one more time, starting from scratch again. Will let you know.

Same problem at the same place - I did everything from scratch.

**Comment by carlalexander** [comment]
Can you show me the config that you're using? (Sorry, I should have asked that earlier.)

**Comment by isaiaholoyede** [comment]
This is what I have:

```ini
# .debops.cfg
# DebOps configuration file
# Nothing added here
```

```ini
# hosts
[debops_all_hosts]
genesis.rccgla.org ansible_python_interpreter=/usr/bin/python3

[wordpress]
genesis.rccgla.org

```

```yaml
---
# inventory/host_vars/genesis.rccgla.org/vars.yml

wordpress__admin_email: 'xxxx@rccgla.org'
wordpress__admin_username: 'xxxxx'
wordpress__title: 'Light Assembly'
wordpress__domain: 'rccgla.org'
wordpress__table_prefix: 'xxxx_wp_'
wordpress__disable_file_edit: True
wordpress__ssl: True
wordpress__ssl_provider: 'letsencrypt' # Default, not necessary.
wordpress__plugins:
  - name: 'google-analytics-dashboard-for-wp'
  - name: 'safe-redirect-manager'     
  - name: 'elasticpress'
  - name: 'redis-cache'
  - name: 'wordpress-seo'
  - name: 'tiny-compress-images'
  - name: 'varnish-http-purge'
wordpress__varnish__add_ban_lurker_headers: True
wordpress__varnish__purge_conditions:
  'req.http.X-Purge-Method ~ "(?i)regex"': |
    ban("obj.http.X-Url ~ " + req.url + " && obj.http.X-Host == " + req.http.host);
    return (synth(200, "Purged"));
```
