### ISSUE TITLE
Replace mariadb role with debops.mariadb

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#9]
Now that DebOps supports Mariadb, there's no need for this project to have its own role.

**Comment by drybjed** [comment]
Actually, you want to use the `debops.mariadb` role as a dependency. Then, you can configure `debops.mariadb_server` either on local or remote host, and point WordPress to it using `debops.mariadb` local facts. There are [examples](http://docs.debops.org/en/latest/ansible/roles/ansible-mariadb/docs/getting-started.html#local-ansible-facts-custom-tasks) in the documentation.

**Comment by carlalexander** [comment]
Oh ok! I'll make sure to look over all of that! I'll change the title to reflect it.

**Comment by carlalexander** [comment]
I tried to get it working today by adding this to the `wordpress` role.

``` yml
  - role: debops.mariadb
    when: wordpress_dependencies is defined and wordpress_dependencies
    tags: [ 'mysql', 'wordpress' ]

    mariadb_databases:
      - name: '{{ wordpress_database_name }}'
        state: 'present'

    mariadb_users:
      - name: '{{ wordpress_database_username }}'
        password: '{{ wordpress_database_password }}'
        host: '{{ wordpress_database_hostname }}'
        priv: '{{ wordpress_database_name }}.*:ALL'
        state: 'present'

  - role: debops.mariadb_server
    when: wordpress_dependencies is defined and wordpress_dependencies
```

`debops.mariadb_server` ends up running first and it breaks. Will have to come on IRC and discuss this.

**Comment by drybjed** [comment]
You don't need to use `debops.mariadb_server` as a dependency in `wordpress` role. Just add that host to `[debops_mariadb_server] Ansible group and run:

```
debops services -t mariadb_server
```

This will install and configure MariaDB on that host. After that, `debops.mariadb` will automatically detect local MariaDB installation and use it.

**Comment by carlalexander** [comment]
This feels like a bit of a regression to me. The goal is to have a standalone `wordpress` application role. That's what you do with `debops.gitlab` and all your other application roles. You put `debops.mysql`as a dependency and the database and its users is all set up for you.

This change means that to using the dependency require assigning the host to another group besides the application group. You also have to run another command.

The behavior you describe is what I'd expect someone to do if we made `wordpress_dependencies: False`. And that's ok if you want to scale the infrastructure. You disable all the dependencies except the application specific ones. You manage everything else yourself across your infrastructure.

It's just not what I'd expect inside an application role by default. I'm sure you have reasons for designing it that way instead of like `debops.mysql`. It's just hard to use it in its current form.

**Comment by drybjed** [comment]
3 lip 2015 14:44 "Carl Alexander" notifications@github.com napisał(a):

> This feels like a bit of a regression to me. The goal is to have a
> wordpress application role like you do with debops.gitlab and all your
> other application roles. You put debops.mysqlas a dependency and the
> database and its users is all set up for you.

I plan to switch GitLab roles to MariaDB after vacation, in a week or so.
Then it all should be clearer in what direction I want to move project
towards. Basically make everything more distributed and decentralized.

> The behavior you describe is what I'd expect someone to do if we made
> wordpress_dependencies: False. And that's ok if you want to scale the
> infrastructure. You disable all the dependencies except the application
> specific ones. You manage everything else yourself across your
> infrastructure.

This behaviour doesn't change all that much. You run the 'debops' command
at the beginning, right? I uses the default playbook which manages the
MariaDB server. You just need to add another 'debops_mariadb_server' group
in inventory and run 'debops' as usual.

> It's just not what I'd expect inside an application role by default. I'm
> sure you have reasons for designing it that way instead of like
> debops.mysql. It's just hard to use it in its current form.

With how MariaDB roles I wanted to rebalance the complexity a bit by making
initial configuration on single host having an additional step vs easier
deployment to remote database from multiple hosts which gives you, for
example, persistent database.

You have default inventory, right? Can you set 1 additional group in it,
run 'debops' command and see how those new roles work together in the end?

Cheers,
Maciej

**Comment by carlalexander** [comment]
I'll run some more tests and let you know. You gave me an idea.

**Comment by ypid** [comment]
@carlalexander I will look into your role, rework it and switch it to `debops.mariadb` the next days.

**Comment by carlalexander** [comment]
Looking at the commit for `debops.mariadb`. One thing, I think I'd change is the host for `mariadb_server`. Is there a way to configure it with a fallback to `wordpress`? It would be a lot nicer for 90% of users who work on a single host.

As usual, I'd like to minimize the complexity for anyone doing using this project. That was my main issue when I started looking into the two roles.

**Comment by ypid** [comment]
Can be done:

playbooks/wordpress.yml

``` YAML
---

- include: common.yml

- name: Manage WordPress web server
  hosts: 'wordpress'
  sudo: True

  roles:
    - role: debops.mariadb_server
      tags: [ 'role::mariadb_server', 'mariadb_server' ]
    - { role: wordpress, tags: wordpress }
```

hosts file unchanged as of master.

Probably makes sense to keep this as simple as possible. I think the `Manage MariaDB server` play is even redundant …
